//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecflowDoJO_DB_Tests
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpecFlowDojo_DBEntities : DbContext
    {
        public SpecFlowDojo_DBEntities()
            : base("name=SpecFlowDojo_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Staging_Customer> Staging_Customer { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<CustomerProfile> CustomerProfile { get; set; }
        public DbSet<Orders> Orders { get; set; }
    }
}
