//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecflowDoJO_DB_Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_Customer
    {
        public int Id { get; set; }
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int LoadStatus { get; set; }
    }
}
